version: "3"
services:
  webscraper:
    container_name: "webscraper"
    build:
      context: ./webscraper
      dockerfile: Dockerfile

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "lottery-domain"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"